#!/usr/bin/env node
import { mkdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));

async function main() {
  const projectName = process.argv[2];
  if (!projectName) {
    console.error('Usage: npx create-seedforge <project-name>');
    process.exit(1);
  }

  const projectPath = resolve(process.cwd(), projectName);

  // Create project directory
  await mkdir(projectPath, { recursive: true });

  // Write .env.example
  await writeFile(
    join(projectPath, '.env.example'),
    '# SeedForge — Database connection\n' +
    '# Uncomment and set your connection string before running the init wizard:\n' +
    '# DATABASE_URL=postgresql://user:password@localhost:5432/seedforge\n',
    'utf-8',
  );

  // Write README.md
  const readmeContent = [
    `# ${projectName}`,
    '',
    'Generated by `npx create-seedforge`.',
    '',
    '## Quick Start',
    '',
    '```bash',
    '# 1. Ensure your database is running',
    '# 2. Scaffold the config file',
    'seedforge init',
    '# 3. Seed your database',
    'seedforge seed',
    '```',
    '',
    'See the [SeedForge documentation](https://github.com/Muhammad-Husnain07/SeedForge) for details.',
    '',
  ].join('\n');
  await writeFile(join(projectPath, 'README.md'), readmeContent, 'utf-8');

  // Run the init wizard by calling the CLI binary from our dependency
  const cliBin = resolve(__dirname, '..', 'node_modules', '.bin', 'seedforge');
  try {
    execSync(`"${cliBin}" init`, { cwd: projectPath, stdio: 'inherit' });
  } catch {
    // Fall back to npx if binary not found locally
    execSync('npx @seed-forge/cli init', { cwd: projectPath, stdio: 'inherit' });
  }

  console.log(`\n✔ Project "${projectName}" created at ${projectPath}`);
  console.log('  Run `cd ' + projectName + ' && seedforge seed` to populate your database.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
