export interface CityRecord {
  city: string;
  region: string;
  country: string;
  countryCode: string;
  latitude: number;
  longitude: number;
}

export const CITIES: CityRecord[] = [
  { city: 'New York', region: 'New York', country: 'United States', countryCode: 'US', latitude: 40.7128, longitude: -74.0060 },
  { city: 'Los Angeles', region: 'California', country: 'United States', countryCode: 'US', latitude: 34.0522, longitude: -118.2437 },
  { city: 'Chicago', region: 'Illinois', country: 'United States', countryCode: 'US', latitude: 41.8781, longitude: -87.6298 },
  { city: 'Houston', region: 'Texas', country: 'United States', countryCode: 'US', latitude: 29.7604, longitude: -95.3698 },
  { city: 'Phoenix', region: 'Arizona', country: 'United States', countryCode: 'US', latitude: 33.4484, longitude: -112.0740 },
  { city: 'Philadelphia', region: 'Pennsylvania', country: 'United States', countryCode: 'US', latitude: 39.9526, longitude: -75.1652 },
  { city: 'San Antonio', region: 'Texas', country: 'United States', countryCode: 'US', latitude: 29.4241, longitude: -98.4936 },
  { city: 'San Diego', region: 'California', country: 'United States', countryCode: 'US', latitude: 32.7157, longitude: -117.1611 },
  { city: 'Dallas', region: 'Texas', country: 'United States', countryCode: 'US', latitude: 32.7767, longitude: -96.7970 },
  { city: 'San Jose', region: 'California', country: 'United States', countryCode: 'US', latitude: 37.3382, longitude: -121.8863 },
  { city: 'Austin', region: 'Texas', country: 'United States', countryCode: 'US', latitude: 30.2672, longitude: -97.7431 },
  { city: 'Jacksonville', region: 'Florida', country: 'United States', countryCode: 'US', latitude: 30.3322, longitude: -81.6557 },
  { city: 'Fort Worth', region: 'Texas', country: 'United States', countryCode: 'US', latitude: 32.7555, longitude: -97.3308 },
  { city: 'Columbus', region: 'Ohio', country: 'United States', countryCode: 'US', latitude: 39.9612, longitude: -82.9988 },
  { city: 'Charlotte', region: 'North Carolina', country: 'United States', countryCode: 'US', latitude: 35.2271, longitude: -80.8431 },
  { city: 'Indianapolis', region: 'Indiana', country: 'United States', countryCode: 'US', latitude: 39.7684, longitude: -86.1581 },
  { city: 'Seattle', region: 'Washington', country: 'United States', countryCode: 'US', latitude: 47.6062, longitude: -122.3321 },
  { city: 'Denver', region: 'Colorado', country: 'United States', countryCode: 'US', latitude: 39.7392, longitude: -104.9903 },
  { city: 'Washington', region: 'District of Columbia', country: 'United States', countryCode: 'US', latitude: 38.9072, longitude: -77.0369 },
  { city: 'Boston', region: 'Massachusetts', country: 'United States', countryCode: 'US', latitude: 42.3601, longitude: -71.0589 },
  { city: 'Nashville', region: 'Tennessee', country: 'United States', countryCode: 'US', latitude: 36.1627, longitude: -86.7816 },
  { city: 'Portland', region: 'Oregon', country: 'United States', countryCode: 'US', latitude: 45.5152, longitude: -122.6784 },
  { city: 'Memphis', region: 'Tennessee', country: 'United States', countryCode: 'US', latitude: 35.1495, longitude: -90.0490 },
  { city: 'Louisville', region: 'Kentucky', country: 'United States', countryCode: 'US', latitude: 38.2527, longitude: -85.7585 },
  { city: 'Baltimore', region: 'Maryland', country: 'United States', countryCode: 'US', latitude: 39.2904, longitude: -76.6122 },
  { city: 'Miami', region: 'Florida', country: 'United States', countryCode: 'US', latitude: 25.7617, longitude: -80.1918 },
  { city: 'Atlanta', region: 'Georgia', country: 'United States', countryCode: 'US', latitude: 33.7490, longitude: -84.3880 },
  { city: 'Milwaukee', region: 'Wisconsin', country: 'United States', countryCode: 'US', latitude: 43.0389, longitude: -87.9065 },
  { city: 'Albuquerque', region: 'New Mexico', country: 'United States', countryCode: 'US', latitude: 35.0853, longitude: -106.6056 },
  { city: 'Tucson', region: 'Arizona', country: 'United States', countryCode: 'US', latitude: 32.2226, longitude: -110.9747 },
  { city: 'London', region: 'England', country: 'United Kingdom', countryCode: 'GB', latitude: 51.5074, longitude: -0.1278 },
  { city: 'Manchester', region: 'England', country: 'United Kingdom', countryCode: 'GB', latitude: 53.4808, longitude: -2.2426 },
  { city: 'Birmingham', region: 'England', country: 'United Kingdom', countryCode: 'GB', latitude: 52.4862, longitude: -1.8904 },
  { city: 'Edinburgh', region: 'Scotland', country: 'United Kingdom', countryCode: 'GB', latitude: 55.9533, longitude: -3.1883 },
  { city: 'Glasgow', region: 'Scotland', country: 'United Kingdom', countryCode: 'GB', latitude: 55.8642, longitude: -4.2518 },
  { city: 'Liverpool', region: 'England', country: 'United Kingdom', countryCode: 'GB', latitude: 53.4084, longitude: -2.9916 },
  { city: 'Leeds', region: 'England', country: 'United Kingdom', countryCode: 'GB', latitude: 53.8008, longitude: -1.5491 },
  { city: 'Bristol', region: 'England', country: 'United Kingdom', countryCode: 'GB', latitude: 51.4545, longitude: -2.5879 },
  { city: 'Toronto', region: 'Ontario', country: 'Canada', countryCode: 'CA', latitude: 43.6532, longitude: -79.3832 },
  { city: 'Vancouver', region: 'British Columbia', country: 'Canada', countryCode: 'CA', latitude: 49.2827, longitude: -123.1207 },
  { city: 'Montreal', region: 'Quebec', country: 'Canada', countryCode: 'CA', latitude: 45.5017, longitude: -73.5673 },
  { city: 'Calgary', region: 'Alberta', country: 'Canada', countryCode: 'CA', latitude: 51.0447, longitude: -114.0719 },
  { city: 'Ottawa', region: 'Ontario', country: 'Canada', countryCode: 'CA', latitude: 45.4215, longitude: -75.6972 },
  { city: 'Sydney', region: 'New South Wales', country: 'Australia', countryCode: 'AU', latitude: -33.8688, longitude: 151.2093 },
  { city: 'Melbourne', region: 'Victoria', country: 'Australia', countryCode: 'AU', latitude: -37.8136, longitude: 144.9631 },
  { city: 'Brisbane', region: 'Queensland', country: 'Australia', countryCode: 'AU', latitude: -27.4698, longitude: 153.0251 },
  { city: 'Perth', region: 'Western Australia', country: 'Australia', countryCode: 'AU', latitude: -31.9505, longitude: 115.8605 },
  { city: 'Adelaide', region: 'South Australia', country: 'Australia', countryCode: 'AU', latitude: -34.9285, longitude: 138.6007 },
  { city: 'Berlin', region: 'Berlin', country: 'Germany', countryCode: 'DE', latitude: 52.5200, longitude: 13.4050 },
  { city: 'Munich', region: 'Bavaria', country: 'Germany', countryCode: 'DE', latitude: 48.1351, longitude: 11.5820 },
  { city: 'Hamburg', region: 'Hamburg', country: 'Germany', countryCode: 'DE', latitude: 53.5511, longitude: 9.9937 },
  { city: 'Frankfurt', region: 'Hesse', country: 'Germany', countryCode: 'DE', latitude: 50.1109, longitude: 8.6821 },
  { city: 'Paris', region: 'Île-de-France', country: 'France', countryCode: 'FR', latitude: 48.8566, longitude: 2.3522 },
  { city: 'Marseille', region: 'Provence-Alpes-Côte d\'Azur', country: 'France', countryCode: 'FR', latitude: 43.2965, longitude: 5.3698 },
  { city: 'Lyon', region: 'Auvergne-Rhône-Alpes', country: 'France', countryCode: 'FR', latitude: 45.7640, longitude: 4.8357 },
  { city: 'Tokyo', region: 'Tokyo', country: 'Japan', countryCode: 'JP', latitude: 35.6762, longitude: 139.6503 },
  { city: 'Osaka', region: 'Osaka', country: 'Japan', countryCode: 'JP', latitude: 34.6937, longitude: 135.5023 },
  { city: 'Kyoto', region: 'Kyoto', country: 'Japan', countryCode: 'JP', latitude: 35.0116, longitude: 135.7681 },
  { city: 'Beijing', region: 'Beijing', country: 'China', countryCode: 'CN', latitude: 39.9042, longitude: 116.4074 },
  { city: 'Shanghai', region: 'Shanghai', country: 'China', countryCode: 'CN', latitude: 31.2304, longitude: 121.4737 },
  { city: 'Mumbai', region: 'Maharashtra', country: 'India', countryCode: 'IN', latitude: 19.0760, longitude: 72.8777 },
  { city: 'Delhi', region: 'Delhi', country: 'India', countryCode: 'IN', latitude: 28.7041, longitude: 77.1025 },
  { city: 'Bangalore', region: 'Karnataka', country: 'India', countryCode: 'IN', latitude: 12.9716, longitude: 77.5946 },
  { city: 'São Paulo', region: 'São Paulo', country: 'Brazil', countryCode: 'BR', latitude: -23.5505, longitude: -46.6333 },
  { city: 'Rio de Janeiro', region: 'Rio de Janeiro', country: 'Brazil', countryCode: 'BR', latitude: -22.9068, longitude: -43.1729 },
  { city: 'Mexico City', region: 'Mexico City', country: 'Mexico', countryCode: 'MX', latitude: 19.4326, longitude: -99.1332 },
  { city: 'Buenos Aires', region: 'Buenos Aires', country: 'Argentina', countryCode: 'AR', latitude: -34.6037, longitude: -58.3816 },
  { city: 'Moscow', region: 'Moscow', country: 'Russia', countryCode: 'RU', latitude: 55.7558, longitude: 37.6173 },
  { city: 'Seoul', region: 'Seoul', country: 'South Korea', countryCode: 'KR', latitude: 37.5665, longitude: 126.9780 },
  { city: 'Istanbul', region: 'Istanbul', country: 'Turkey', countryCode: 'TR', latitude: 41.0082, longitude: 28.9784 },
  { city: 'Dubai', region: 'Dubai', country: 'United Arab Emirates', countryCode: 'AE', latitude: 25.2048, longitude: 55.2708 },
  { city: 'Singapore', region: 'Singapore', country: 'Singapore', countryCode: 'SG', latitude: 1.3521, longitude: 103.8198 },
  { city: 'Bangkok', region: 'Bangkok', country: 'Thailand', countryCode: 'TH', latitude: 13.7563, longitude: 100.5018 },
  { city: 'Amsterdam', region: 'North Holland', country: 'Netherlands', countryCode: 'NL', latitude: 52.3676, longitude: 4.9041 },
  { city: 'Madrid', region: 'Madrid', country: 'Spain', countryCode: 'ES', latitude: 40.4168, longitude: -3.7038 },
  { city: 'Rome', region: 'Lazio', country: 'Italy', countryCode: 'IT', latitude: 41.9028, longitude: 12.4964 },
  { city: 'Stockholm', region: 'Stockholm', country: 'Sweden', countryCode: 'SE', latitude: 59.3293, longitude: 18.0686 },
  { city: 'Oslo', region: 'Oslo', country: 'Norway', countryCode: 'NO', latitude: 59.9139, longitude: 10.7522 },
  { city: 'Copenhagen', region: 'Capital Region', country: 'Denmark', countryCode: 'DK', latitude: 55.6761, longitude: 12.5683 },
  { city: 'Zurich', region: 'Zürich', country: 'Switzerland', countryCode: 'CH', latitude: 47.3769, longitude: 8.5417 },
  { city: 'Warsaw', region: 'Masovia', country: 'Poland', countryCode: 'PL', latitude: 52.2297, longitude: 21.0122 },
  { city: 'Prague', region: 'Prague', country: 'Czech Republic', countryCode: 'CZ', latitude: 50.0755, longitude: 14.4378 },
  { city: 'Budapest', region: 'Budapest', country: 'Hungary', countryCode: 'HU', latitude: 47.4979, longitude: 19.0402 },
  { city: 'Vienna', region: 'Vienna', country: 'Austria', countryCode: 'AT', latitude: 48.2082, longitude: 16.3738 },
  { city: 'Dublin', region: 'Leinster', country: 'Ireland', countryCode: 'IE', latitude: 53.3498, longitude: -6.2603 },
  { city: 'Brussels', region: 'Brussels-Capital', country: 'Belgium', countryCode: 'BE', latitude: 50.8503, longitude: 4.3517 },
  { city: 'Lisbon', region: 'Lisbon', country: 'Portugal', countryCode: 'PT', latitude: 38.7223, longitude: -9.1393 },
  { city: 'Athens', region: 'Attica', country: 'Greece', countryCode: 'GR', latitude: 37.9838, longitude: 23.7275 },
  { city: 'Helsinki', region: 'Uusimaa', country: 'Finland', countryCode: 'FI', latitude: 60.1699, longitude: 24.9384 },
  { city: 'Auckland', region: 'Auckland', country: 'New Zealand', countryCode: 'NZ', latitude: -36.8485, longitude: 174.7633 },
  { city: 'Cape Town', region: 'Western Cape', country: 'South Africa', countryCode: 'ZA', latitude: -33.9249, longitude: 18.4241 },
  { city: 'Nairobi', region: 'Nairobi', country: 'Kenya', countryCode: 'KE', latitude: -1.2921, longitude: 36.8219 },
  { city: 'Lagos', region: 'Lagos', country: 'Nigeria', countryCode: 'NG', latitude: 6.5244, longitude: 3.3792 },
  { city: 'Cairo', region: 'Cairo', country: 'Egypt', countryCode: 'EG', latitude: 30.0444, longitude: 31.2357 },
  { city: 'Casablanca', region: 'Casablanca-Settat', country: 'Morocco', countryCode: 'MA', latitude: 33.5731, longitude: -7.5898 },
  { city: 'Bogotá', region: 'Bogotá', country: 'Colombia', countryCode: 'CO', latitude: 4.7110, longitude: -74.0721 },
  { city: 'Lima', region: 'Lima', country: 'Peru', countryCode: 'PE', latitude: -12.0464, longitude: -77.0428 },
  { city: 'Santiago', region: 'Santiago', country: 'Chile', countryCode: 'CL', latitude: -33.4489, longitude: -70.6693 },
  { city: 'Jakarta', region: 'Jakarta', country: 'Indonesia', countryCode: 'ID', latitude: -6.2088, longitude: 106.8456 },
  { city: 'Manila', region: 'Metro Manila', country: 'Philippines', countryCode: 'PH', latitude: 14.5995, longitude: 120.9842 },
  { city: 'Ho Chi Minh City', region: 'Southeast', country: 'Vietnam', countryCode: 'VN', latitude: 10.8231, longitude: 106.6297 },
  { city: 'Kuala Lumpur', region: 'Kuala Lumpur', country: 'Malaysia', countryCode: 'MY', latitude: 3.1390, longitude: 101.6869 },
  { city: 'Reykjavik', region: 'Capital Region', country: 'Iceland', countryCode: 'IS', latitude: 64.1466, longitude: -21.9426 },
];